name: 🚀 Publish to NPM
on:
  release:
    types: [created]
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Cache node_modules but bust that cache any time the pnpm-lock.yaml file changes.
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm i

      - name: Build CLI tool 🔧
        run: pnpm build

      - name: Publish package on NPM 📦
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
